apiVersion: v1
kind: Pod
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  containers:
    -
      name: redis-master
      image: mceith/redis-master:latest
      ports:
        - containerPort: 6379

---


apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis-master